"""Add tube_axis field to Project

Revision ID: 4ce6f3870477
Revises: a96988c7494a
Create Date: 2026-01-20 19:44:31.896451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce6f3870477'
down_revision = 'a96988c7494a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tube_axis', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('tube_axis')

    # ### end Alembic commands ###
