"""Initial models

Revision ID: 5fadbc454cd5
Revises: 
Create Date: 2026-01-17 21:21:53.429228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fadbc454cd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('safety_height', sa.Float(), nullable=True),
    sa.Column('travel_height', sa.Float(), nullable=True),
    sa.Column('spindle_warmup_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('max_x', sa.Float(), nullable=True),
    sa.Column('max_y', sa.Float(), nullable=True),
    sa.Column('units', sa.String(length=10), nullable=True),
    sa.Column('controller_type', sa.String(length=20), nullable=True),
    sa.Column('supports_subroutines', sa.Boolean(), nullable=True),
    sa.Column('supports_canned_cycles', sa.Boolean(), nullable=True),
    sa.Column('gcode_base_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('base_material', sa.String(length=50), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('thickness', sa.Float(), nullable=True),
    sa.Column('outer_width', sa.Float(), nullable=True),
    sa.Column('outer_height', sa.Float(), nullable=True),
    sa.Column('wall_thickness', sa.Float(), nullable=True),
    sa.Column('gcode_standards', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_type', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('size_unit', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('project_type', sa.String(length=20), nullable=False),
    sa.Column('material_id', sa.String(length=50), nullable=True),
    sa.Column('drill_tool_id', sa.Integer(), nullable=True),
    sa.Column('end_mill_tool_id', sa.Integer(), nullable=True),
    sa.Column('operations', sa.JSON(), nullable=False),
    sa.Column('tube_void_skip', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['drill_tool_id'], ['tool.id'], ),
    sa.ForeignKeyConstraint(['end_mill_tool_id'], ['tool.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('tool')
    op.drop_table('material')
    op.drop_table('machine_settings')
    op.drop_table('general_settings')
    # ### end Alembic commands ###
