"""Add working_length and tube_orientation to Project

Revision ID: 6e4d56d938b6
Revises: 5fadbc454cd5
Create Date: 2026-01-19 16:00:12.634288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4d56d938b6'
down_revision = '5fadbc454cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tube_orientation', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('tube_orientation')
        batch_op.drop_column('working_length')

    # ### end Alembic commands ###
