"""Add arc slowdown settings

Revision ID: 87a3057c6348
Revises: ecb2bce783ea
Create Date: 2026-01-24 21:29:13.265194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a3057c6348'
down_revision = 'ecb2bce783ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ramp_angle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('arc_slowdown_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('arc_feed_factor', sa.Float(), nullable=True))
        batch_op.drop_column('lead_in_distance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_in_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('arc_feed_factor')
        batch_op.drop_column('arc_slowdown_enabled')
        batch_op.drop_column('ramp_angle')

    # ### end Alembic commands ###
