"""Add safety settings columns to GeneralSettings

Revision ID: a96988c7494a
Revises: fccb8328ebc9
Create Date: 2026-01-20 00:14:57.582922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96988c7494a'
down_revision = 'fccb8328ebc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('helix_pitch', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('first_pass_feed_factor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_stepdown_factor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('corner_slowdown_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('corner_feed_factor', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('corner_feed_factor')
        batch_op.drop_column('corner_slowdown_enabled')
        batch_op.drop_column('max_stepdown_factor')
        batch_op.drop_column('first_pass_feed_factor')
        batch_op.drop_column('helix_pitch')

    # ### end Alembic commands ###
