"""Add tip_compensation field to Tool model

Revision ID: b29e31da8c88
Revises: 4ce6f3870477
Create Date: 2026-01-21 07:11:56.103082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29e31da8c88'
down_revision = '4ce6f3870477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tip_compensation', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('tip_compensation')

    # ### end Alembic commands ###
