"""Add allow_negative_coordinates to GeneralSettings

Revision ID: c20bfde4d449
Revises: b29e31da8c88
Create Date: 2026-01-24 16:19:07.491917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20bfde4d449'
down_revision = 'b29e31da8c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_negative_coordinates', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('allow_negative_coordinates')

    # ### end Alembic commands ###
