"""Add per-cut-type lead-in settings

Revision ID: e2e6658593d1
Revises: c20bfde4d449
Create Date: 2026-01-24 16:49:39.636163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e6658593d1'
down_revision = 'c20bfde4d449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # First add new columns
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circle_lead_in_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hexagon_lead_in_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('line_lead_in_type', sa.String(length=20), nullable=True))

    # Migrate existing lead_in_type value to new columns
    # For circles and hexagons, use the existing value
    # For lines, use 'ramp' if existing was 'helical' (since lines don't support helical)
    op.execute("""
        UPDATE general_settings
        SET circle_lead_in_type = COALESCE(lead_in_type, 'helical'),
            hexagon_lead_in_type = COALESCE(lead_in_type, 'helical'),
            line_lead_in_type = CASE
                WHEN lead_in_type = 'helical' THEN 'ramp'
                ELSE COALESCE(lead_in_type, 'ramp')
            END
    """)

    # Now drop the old column
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('lead_in_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_in_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('line_lead_in_type')
        batch_op.drop_column('hexagon_lead_in_type')
        batch_op.drop_column('circle_lead_in_type')

    # ### end Alembic commands ###
