"""Add cut_through_buffer to GeneralSettings

Revision ID: ecb2bce783ea
Revises: e2e6658593d1
Create Date: 2026-01-24 18:25:47.302558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb2bce783ea'
down_revision = 'e2e6658593d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cut_through_buffer', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('cut_through_buffer')

    # ### end Alembic commands ###
