"""Add lead-in settings to GeneralSettings

Revision ID: fccb8328ebc9
Revises: 6e4d56d938b6
Create Date: 2026-01-19 23:16:23.301571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fccb8328ebc9'
down_revision = '6e4d56d938b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_in_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('lead_in_distance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('lead_in_distance')
        batch_op.drop_column('lead_in_type')

    # ### end Alembic commands ###
