# Tool Types
TOOL_TYPE_DRILL = 'drill'
TOOL_TYPE_END_MILL_1FLUTE = 'end_mill_1flute'
TOOL_TYPE_END_MILL_2FLUTE = 'end_mill_2flute'

VALID_TOOL_TYPES = [TOOL_TYPE_DRILL, TOOL_TYPE_END_MILL_1FLUTE, TOOL_TYPE_END_MILL_2FLUTE]

# Project Types
PROJECT_TYPE_DRILL = 'drill'
PROJECT_TYPE_CUT = 'cut'

VALID_PROJECT_TYPES = [PROJECT_TYPE_DRILL, PROJECT_TYPE_CUT]

# Material Forms
MATERIAL_FORM_SHEET = 'sheet'
MATERIAL_FORM_TUBE = 'tube'

VALID_MATERIAL_FORMS = [MATERIAL_FORM_SHEET, MATERIAL_FORM_TUBE]

# Operation Types
OP_TYPE_SINGLE = 'single'
OP_TYPE_PATTERN_LINEAR = 'pattern_linear'
OP_TYPE_PATTERN_GRID = 'pattern_grid'

VALID_OPERATION_TYPES = [OP_TYPE_SINGLE, OP_TYPE_PATTERN_LINEAR, OP_TYPE_PATTERN_GRID]

# Line Types (for line cuts)
LINE_TYPE_START = 'start'
LINE_TYPE_STRAIGHT = 'straight'
LINE_TYPE_ARC = 'arc'

VALID_LINE_TYPES = [LINE_TYPE_START, LINE_TYPE_STRAIGHT, LINE_TYPE_ARC]
